name: Oy(TM) a daily comic
markdown: redcarpet
pygments: true
permalink: :title
future: false
paginate: 1
url: http://oycomics.com
description: Daily all-ages comedy-drama.
author: Danny Burleson
rss_post_limit: 10
