name: Oy(TM) a daily comic
markdown: redcarpet
pygments: true
permalink: :title
future: false
paginate: 1
url: http://oycomics.com
description: Follow the adventures at a family entertainment company . . . and the lives of the people who work there.
author: Danny Burleson
rss_post_limit: 10
